---
- name: Set time zone
  timezone:
    name: '{{ ntp.timezone if ntp.timezone is defined else "Etc/UTC" }}'

- name: Configure NTP service configuration
  template:
    src: ntp.j2
    dest: /etc/ntp.conf
    mode: 0644
  notify:
    - stop ntp in default vrf
    - restart ntp in mgmt vrf

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
