---
loopback:
  ips:
    - "{{ vxlan_local_loopback }}"
  vxlan_local_tunnel_ip: "{{ vxlan_local_loopback | ipaddr('address') }}"
  pim:
    source: "{{ pim.source }}"
  igmp: true
global_anycast_mac: "{{ evpn_mh_sysmac_prefix }}:{{ sysmac }}"
eth0:
  ips:
    - "{{ eth0_ip }}"
netq_agent_fa:
  latency: "{{ netq_agent_conf.latency }}"
  buffer_occ: "{{ netq_agent_conf.buffer_occ }}"
interfaces:
  - name: swp51
    options: "{{ leaf_spine_interface }}"
  - name: swp52
    options: "{{ leaf_spine_interface }}"
  - name: swp53
    options: "{{ leaf_spine_interface }}"
  - name: swp54
    options: "{{ leaf_spine_interface }}"
bonds:
  - name: bond1
    ports: [swp1]
    es_id: 1
    es_df_pref: "{{ es_df_pref | default() }}"
    bridge:
      access: 10
    options:
      mtu: 9000
      extras:
        - bond-lacp-bypass-allow yes
        - mstpctl-bpduguard yes
        - mstpctl-portadminedge yes
  - name: bond2
    ports: [swp2]
    es_id: 2
    es_df_pref: "{{ es_df_pref | default() }}"
    bridge:
      access: 20
    options:
      mtu: 9000
      extras:
        - bond-lacp-bypass-allow yes
        - mstpctl-bpduguard yes
        - mstpctl-portadminedge yes
  - name: bond3
    ports: [swp3]
    es_id: 3
    es_df_pref: "{{ es_df_pref | default() }}"
    bridge:
      access: 30
    options:
      mtu: 9000
      extras:
        - bond-lacp-bypass-allow yes
        - mstpctl-bpduguard yes
        - mstpctl-portadminedge yes
vnis_vrr:
  - "{{ vni10 }}"
  - "{{ vni20 }}"
  - "{{ vni30 }}"
  - "{{ vniRED }}"
  - "{{ vniBLUE }}"
bridge:
  ports:
    - "{{ vni10.name }}"
    - "{{ vni20.name }}"
    - "{{ vni30.name }}"
    - "{{ vniRED.name }}"
    - "{{ vniBLUE.name }}"
    - "bond1"
    - "bond2"
    - "bond3"
  vids:
    - 10
    - 20
    - 30
evpn_mh:
  sysmac: "{{ evpn_mh_sysmac_prefix }}:{{ sysmac }}"
  startup_delay: 10
vlans:
  - "{{ vlan10 }}"
  - "{{ vlan20 }}"
  - "{{ vlan30 }}"
  - "{{ vlan4001 }}"
  - "{{ vlan4002 }}"
vrfs:
  - "{{ vrf_mgmt }}"
  - "{{ vrf_RED }}"
  - "{{ vrf_BLUE }}"
bgp:
  asn: "{{ bgp_asn_prefix }}0{{ id }}"
  router_id: "{{ vxlan_local_loopback | ipaddr('address') }}"
  peergroups:
    - {name: underlay, remote_as: external}
  neighbors:
    - {interface: swp51, unnumbered: true, peergroup: underlay}
    - {interface: swp52, unnumbered: true, peergroup: underlay}
    - {interface: swp53, unnumbered: true, peergroup: underlay}
    - {interface: swp54, unnumbered: true, peergroup: underlay}
  address_family:
    - name: ipv4_unicast
      redistribute:
        - {type: connected}
    - name: l2vpn_evpn
      neighbors:
        - {interface: underlay, activate: true}
      advertise_all_vni: true
      advertise_svi_ip: true
  vrfs:
    - name: RED
      router_id: "{{ vxlan_local_loopback | ipaddr('address') }}"
      vxlan_id_nvue: 4001
      address_family:
        - name: ipv4_unicast
          redistribute:
            - {type: connected}
        - name: l2vpn_evpn
          extras:
            - "advertise ipv4 unicast"
    - name: BLUE
      router_id: "{{ vxlan_local_loopback | ipaddr('address') }}"
      vxlan_id_nvue: 4002
      address_family:
        - name: ipv4_unicast
          redistribute:
            - {type: connected}
        - name: l2vpn_evpn
          extras:
            - "advertise ipv4 unicast"
pim:
  address_family:
    - name: ipv4-unicast
  source: "{{ bgp.router_id|default() }}"
  ecmp: true
  keep_alive: 3600
  rp_mcast_range: 224.1.1.0/24
  rpaddr: 10.10.100.100/32