---
- name: stop ntp in default vrf
  service:
    name: ntp
    state: stopped
    enabled: false

- name: restart ntp in mgmt vrf
  service:
    name: ntp@mgmt
    state: restarted
    enabled: true
