---
- hosts: DCI
  become: yes
  gather_facts: false
  tasks:
    - name: Fetch startup.yaml
      fetch: dest={{my_variable}}/{{inventory_hostname}}/startup.yaml src=/etc/nvue.d/startup.yaml flat=yes

- hosts: server
  become: yes
  gather_facts: false
  tasks:
    - name: Fetch config.yaml
      fetch: dest={{my_variable}}/{{inventory_hostname}}/config.yaml src=/etc/netplan/config.yaml flat=yes
