---
- hosts: DCI
  become: yes
  gather_facts: false
  tasks:
    - name: Restore Switch - startup.yaml
      copy: src={{my_variable}}/{{inventory_hostname}}/startup.yaml dest=/etc/nvue.d/startup.yaml
    
    - name: Config replace
      command: nv config replace /etc/nvue.d/startup.yaml

    - name : Switch - Config apply
      command: nv config apply startup -y

      #    - name : Restart FRR process just in case
      # command : service frr restart
    
      #    - name : Restart  Switch
      #      command: reboot

- hosts: server
  become: yes
  gather_facts: false
  tasks:
    - name: Restore Server - config.yaml
      copy: src={{my_variable}}/{{inventory_hostname}}/config.yaml dest=/etc/netplan/config.yaml

    - name : Server - Config apply
      command: netplan apply
