---
- name: Set MOTD
  copy:
    content: "{{ ssh.motd }}"
    dest: /etc/motd
    mode: 0644
  when: ssh is defined and ssh.motd is defined

- name: Set pre login banner
  template:
    src: issue.net.j2
    dest: /etc/issue.net
    mode: 0755

- name: Enable pre login banner
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#Banner"
    line: "Banner /etc/issue.net"
  notify: restart ssh

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
