---
- name: Set MOTD on hosts
  copy:
    content: "{{ ssh.motd }}"
    dest: /etc/motd
    mode: 0644
  when: ssh is defined and ssh.motd is defined
  notify: restart ssh

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
