---
- name: Ensure systemwide MTU
  copy:
    content: |
      {
        "address":
        {
          "defaults":
          { "mtu": "9216" },
          "iface_defaults":
          {
            "eth0":
            { "mtu": "1500" }
          }
        }
      }
    dest: /etc/network/ifupdown2/policy.d/mtu.json
    mode: 0644
  notify: apply interface changes

- name: toggle evpn multihoming knob in switchd
  lineinfile:
    path: "/etc/cumulus/switchd.conf"
    regexp: "^#evpn.multihoming.enable"
    line: "evpn.multihoming.enable=TRUE"
  notify: restart switchd

- name: Configure interfaces
  template:
    src: "interfaces.j2"
    dest: /etc/network/interfaces
    validate: ifup -a -s -i %s
    mode: 0644
  notify: apply interface changes

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
