---
- name: restart networking
  become: true
  command: ifreload -a

- name: restart ntp
  service:
    name: ntp
    state: restarted
    enabled: true

- name: restart lldpd
  service:
    name: lldpd
    state: restarted
    enabled: true
