---
- name: restart networking
  become: true
  command: ifreload -a

- name: restart lldpd
  service:
    name: lldpd
    state: restarted
    enabled: true

- name: restart chrony
  service:
    name: chrony
    state: restarted
    enabled: true