- name: restart auditd
  service:
    name: auditd
    state: restarted
    enabled: true

- name: restart nclu
  service:
    name: netd
    state: restarted
    enabled: true

- name: restart syslog
  service:
    name: rsyslog
    state: restarted
    enabled: true
