---
- name: Remove apps3 http source
  ansible.builtin.apt_repository:
    repo: deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-4 netq-latest
    state: absent
    filename: apps3_cumulusnetworks_com_repos_deb

- name: Add apps3 https source
  ansible.builtin.apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb CumulusLinux-4 netq-latest
    state: present
    filename: apps3_cumulusnetworks_com_repos_deb
