---
- hosts: spine leaf border
  become: true
  gather_facts: false
  roles:
    - {role: tacacs_client, tags: ["tacacs_client"]}
    - {role: nvue, tags: ["nvue"]}
    - {role: ssh, tags: ["ssh"]}
    - {role: backup, tags: ["backup"]}
  vars:
    ansible_python_interpreter: /usr/bin/python3

- hosts: server fw
  become: true
  gather_facts: false
  roles:
    - {role: servers, tags: ["servers"]}
    - {role: backup, tags: ["backup"]}
    - {role: motd, tags: ["motd"]}
    - {role: ssh, tags: ["ssh"]}

- hosts: localhost
  become: true
  gather_facts: false
  roles:
    - {role: tacacs_server, tags: ["tacacs_server"]}
    - {role: snmp, tags: ["snmp"]}
