---
- name: Remove apps3 http source
  ansible.builtin.apt_repository:
    repo: deb http://apps3.cumulusnetworks.com/repos/deb bionic netq-latest
    state: absent
    filename: apps3_cumulusnetworks_com_repos_deb

- name: Add apps3 https source
  ansible.builtin.apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb CumulusLinux-4 netq-latest
    state: present
    filename: apps3_cumulusnetworks_com_repos_deb

- name: Package installs
  apt:
    pkg:
      - ntp
      - lldpd
    state: present

- name: Set time zone
  timezone:
    name: "{{ ntp.timezone }}"

- name: Configure NTP service configuration
  template:
    src: ntp.j2
    dest: /etc/ntp.conf
    mode: 0644
  notify: restart ntp

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Copy lldp configuration
  copy:
    src: port_info.conf
    dest: /etc/lldpd.d/port_info.conf
    mode: 0644
  notify: restart lldpd

- name: Push interfaces config to servers
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    mode: 0644
  notify: restart networking
