---
- name: Package installs
  apt:
    pkg:
      - lldpd
      - ifupdown2
      - chrony
      - iperf
    state: present

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Copy lldp configuration
  copy:
    src: port_info.conf
    dest: /etc/lldpd.d/port_info.conf
    mode: 0644
  notify: restart lldpd

- name: Push interfaces config to servers
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    mode: 0644
  notify: restart networking
  when: 
    - inventory_hostname in groups["server"]
    - inventory_hostname != 'server07'
    - inventory_hostname != 'server08'
    
- name: Push interfaces config to unused servers
  template:
    src: interfaces_unused_srv.j2
    dest: /etc/network/interfaces
    mode: 0644
  notify: restart networking
  when: (inventory_hostname in groups["fw"]) or (inventory_hostname == 'server07') or (inventory_hostname == 'server08')
